# [K] (c) 2020

name: UPDATE

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/main.yml'
jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/adbyby'
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: master

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Git Init
      run:  |
        git clone -b master --single-branch https://github.com/coolsnowwolf/lede.git /tmp/lede
        cp -rf /tmp/lede/package/lean/adbyby/* ./
        git add .
        git commit -m "update from upstream." || echo ""
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run:  |
        git push origin $DOWNSTREAM_BRANCH || echo ""
